---
# Get a token at https://github.com/settings/tokens/new to improve rate limit
GithubToken: ~
# Select a colorscheme you want to use
Colorscheme: "solarized-dark"

# Scheme and template list URLs default to the following but can be overridden if you wish
SchemesMasterURL: "https://raw.githubusercontent.com/chriskempson/base16-schemes-source/master/list.yaml"
TemplatesMasterURL: "https://raw.githubusercontent.com/chriskempson/base16-templates-source/master/list.yaml"

# Enable/Disable dry-run. If enabled no configs will be altered
DryRun: false
# Set the applications templates you want to render to true
applications:
    dunst:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    fzf:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    gtk-flatcolor:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          gtk-2:
            path: ~/.gtkrc-2.0
            mode: rewrite
          gtk-3:
            path: ~/.config/gtk-3.0/gtk.css
            mode: rewrite
    kitty:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: ~/.config/kitty/theme.conf
            mode: rewrite
    qutebrowser:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    rofi:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: ~/.config/rofi/base16-theme.rasi
            mode: rewrite
    shell:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: ~/.base16_theme
            mode: rewrite
    sway:
        enabled: true
        hook: swaymsg reload
        files:
          colors:
            path: ~/.config/sway/theme.conf
            mode: rewrite
    tmux:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            mode: rewrite
            path: ~/.tmux.conf.theme
    vim:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: ~/.vim/colors/base16.vim
            mode: rewrite
    vscode:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    waybar:
        enable: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: ~/.config/waybar/style.css
            mode: rewrite
    wofi:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: ~/.config/wofi/style.css
            mode: rewrite
    xresources:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: ~/.Xresources
            mode: rewrite
