---
# Get a token at https://github.com/settings/tokens/new to improve rate limit
GithubToken: ""
# Select a colorscheme you want to use
Colorscheme: "google-dark"

# Scheme and template list URLs default to the following but can be overridden if you wish
SchemesMasterURL: "https://raw.githubusercontent.com/chriskempson/base16-schemes-source/master/list.yaml"
TemplatesMasterURL: "https://raw.githubusercontent.com/chriskempson/base16-templates-source/master/list.yaml"

# Enable/Disable dry-run. If enabled no configs will be altered
DryRun: false
# Set the applications templates you want to render to true
applications:
    dunst:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    fzf:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    gtk2:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    jetbrains:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    kitty:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    qutebrowser:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    rofi:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    shell:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    tmux:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    vim:
        enabled: true
        mode: rewrite
        hook: ""
        files:
          default:
            path: ~/.vim/colors/base16.vim
            mode: rewrite
    vscode:
        enabled: true
        mode: rewrite
        hook: ""
        files:
    xresources:
        enabled: true
        mode: rewrite
        hook: ""
        files:
